Repository Learnable-capstone/Learnable-BE, pull requests merged in 2023-03, with the labels that each got.

#3 docker-compose local 테스트 DB 구성 작업
  docker/README.md
  docker/docker-compose-local-m.yml
  docker/docker-compose-local.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 📖 문서 작업

#7 HTTP 응답 상태코드와 메시지 구성하기
  src/main/java/dev/be/learnable/common/CodeAndMessages.java
  src/main/java/dev/be/learnable/common/exception/BaseException.java
  src/main/java/dev/be/learnable/common/exception/ErrorCodeAndMessages.java
  src/main/java/dev/be/learnable/common/exception/GlobalExceptionHandler.java
  src/main/java/dev/be/learnable/common/response/BaseResponse.java
  src/main/java/dev/be/learnable/common/response/ResponseCodeAndMessages.java
Labels: 👨‍👩‍👧‍👦 공통 작업

#8 러너블 ERD 설계
  document/learnable-erd.png
Labels: 📖 문서 작업, 👨‍👩‍👧‍👦 공통 작업

#11 도메인 설계
  src/main/java/dev/be/learnable/common/config/JpaConfig.java
  src/main/java/dev/be/learnable/core/domain/BaseEntity.java
  src/main/java/dev/be/learnable/core/domain/BotMessage.java
  src/main/java/dev/be/learnable/core/domain/ChatRoom.java
  src/main/java/dev/be/learnable/core/domain/Member.java
  src/main/java/dev/be/learnable/core/domain/Question.java
  src/main/java/dev/be/learnable/core/domain/Subject.java
  src/main/java/dev/be/learnable/core/domain/UserMessage.java
  src/main/java/dev/be/learnable/core/dto/ChatRoomDto.java
  src/main/java/dev/be/learnable/core/dto/MemberDto.java
  src/main/java/dev/be/learnable/core/dto/QuestionDto.java
  src/main/java/dev/be/learnable/core/dto/SubjectDto.java
  src/main/resources/application.yml
Labels: 🛠️ 기능 구현

#13 Feature/#10/chatgpt init
  .gitignore
  build.gradle
  src/main/java/dev/be/learnable/LearnableApplication.java
  src/main/java/dev/be/learnable/common/config/OpenAIClientConfig.java
  src/main/java/dev/be/learnable/core/dto/ChatGPTRequest.java
  src/main/java/dev/be/learnable/core/dto/ChatGPTResponse.java
  src/main/java/dev/be/learnable/core/dto/ChatRequest.java
  src/main/java/dev/be/learnable/core/dto/Choice.java
  src/main/java/dev/be/learnable/core/dto/Message.java
  src/main/java/dev/be/learnable/core/dto/Usage.java
  src/main/java/dev/be/learnable/core/service/OpenAIClient.java
  src/main/java/dev/be/learnable/core/service/OpenAIClientService.java
  src/main/java/dev/be/learnable/core/web/ChatController.java
Labels: 🛠️ 기능 구현, 🏘️ 인프라 작업

#14 JPA repository 생성 및 테스트
  build.gradle
  docker/config/mysql.cnf
  docker/docker-compose-local-m.yml
  docker/docker-compose-local.yml
  src/main/java/dev/be/learnable/core/repository/BotMessageRepository.java
  src/main/java/dev/be/learnable/core/repository/ChatRoomRepository.java
  src/main/java/dev/be/learnable/core/repository/MemberRepository.java
  src/main/java/dev/be/learnable/core/repository/QuestionRepository.java
  src/main/java/dev/be/learnable/core/repository/SubjectRepository.java
  src/main/java/dev/be/learnable/core/repository/UserMessageRepository.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
  src/test/java/dev/be/learnable/LearnableApplicationTests.java
  src/test/java/dev/be/learnable/repository/JpaRepositoryTest.java
Labels: 🛠️ 기능 구현, 🗡️ 테스트

#17 Swagger 설정
  build.gradle
  src/main/resources/application-local.yml
Labels: 📖 문서 작업, 👨‍👩‍👧‍👦 공통 작업
