Repository Learnable-capstone/Learnable-BE, pull requests merged in 2023-04, with the labels that each got.

#19 Feature/#1/login google
  build.gradle
  src/main/java/dev/be/learnable/common/config/SecurityConfig.java
  src/main/java/dev/be/learnable/core/domain/Member.java
  src/main/java/dev/be/learnable/core/dto/MemberDto.java
  src/main/java/dev/be/learnable/core/repository/MemberRepository.java
  src/main/java/dev/be/learnable/oauth/OAuthAttributes.java
  src/main/java/dev/be/learnable/oauth/OAuthService.java
  src/main/resources/data.sql
Labels: 🛠️ 기능 구현

#20 채팅방 관련 API 구현
  .gitignore
  build.gradle
  src/main/java/dev/be/learnable/common/exception/ErrorCodeAndMessages.java
  src/main/java/dev/be/learnable/common/exception/NotFoundBotMessageException.java
  src/main/java/dev/be/learnable/common/exception/NotFoundChatRoomException.java
  src/main/java/dev/be/learnable/common/response/ResponseCodeAndMessages.java
  src/main/java/dev/be/learnable/core/domain/BotMessage.java
  src/main/java/dev/be/learnable/core/dto/ChatRoomDto.java
  src/main/java/dev/be/learnable/core/dto/QuestionDto.java
  src/main/java/dev/be/learnable/core/dto/request/ChatRoomRequest.java
  src/main/java/dev/be/learnable/core/dto/response/BotMessageResponse.java
  src/main/java/dev/be/learnable/core/dto/response/ChatRoomDetailResponse.java
  src/main/java/dev/be/learnable/core/dto/response/ChatRoomResponse.java
  src/main/java/dev/be/learnable/core/dto/response/ChatRoomsResponse.java
  src/main/java/dev/be/learnable/core/dto/response/UserMessageResponse.java
  src/main/java/dev/be/learnable/core/repository/BotMessageRepository.java
  src/main/java/dev/be/learnable/core/repository/ChatRoomRepository.java
  src/main/java/dev/be/learnable/core/repository/UserMessageRepository.java
  src/main/java/dev/be/learnable/core/service/ChatRoomService.java
  src/main/java/dev/be/learnable/core/web/ChatRoomController.java
  src/test/java/dev/be/learnable/core/service/ChatRoomServiceTest.java
  src/test/java/dev/be/learnable/core/web/ChatRoomControllerTest.java
Labels: 🛠️ 기능 구현, 🗡️ 테스트

#23 refactor: [#22] yml 파일 수정 및 gitignore에서 삭제
  .gitignore
  src/main/resources/application-local.yml
Labels: 💡리팩토링
