Repository Learnable-capstone/Learnable-BE, pull requests merged in 2023-05, with the labels that each got.

#26 refactor: [#24] CS지식 data-set 추가
  src/main/resources/data.sql
Labels: 📖 문서 작업, 💡리팩토링

#33 Refactor/#32/answer
  src/main/java/dev/be/learnable/core/domain/Question.java
  src/main/java/dev/be/learnable/core/dto/QuestionDto.java
  src/main/java/dev/be/learnable/core/service/OpenAIClientService.java
  src/main/resources/data.sql
Labels: 💡리팩토링

#38 Feature/#35/message
  src/main/java/dev/be/learnable/core/domain/BotMessage.java
  src/main/java/dev/be/learnable/core/repository/BotMessageRepository.java
  src/main/java/dev/be/learnable/core/service/BotMessageService.java
  src/main/java/dev/be/learnable/core/web/BotMessageController.java
  src/main/resources/data.sql
Labels: 🛠️ 기능 구현, 🗡️ 테스트

#40 refactor: [#39] 채팅방 삭제 수정
  src/main/java/dev/be/learnable/core/repository/BotMessageRepository.java
  src/main/java/dev/be/learnable/core/repository/UserMessageRepository.java
  src/main/java/dev/be/learnable/core/service/ChatRoomService.java
Labels: 💡리팩토링

#41 점수 파싱 기능 추가
  src/main/java/dev/be/learnable/core/domain/ChatRoom.java
  src/main/java/dev/be/learnable/core/dto/ChatRoomDto.java
  src/main/java/dev/be/learnable/core/dto/request/ChatRoomRequest.java
  src/main/java/dev/be/learnable/core/dto/response/ChatRoomResponse.java
  src/main/java/dev/be/learnable/core/service/OpenAIClientService.java
  src/main/java/dev/be/learnable/core/web/UserMessageController.java
  src/main/resources/data.sql
  src/test/java/dev/be/learnable/core/service/ChatRoomServiceTest.java
Labels: 🛠️ 기능 구현
